"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _paseadores_rejilla from './paseadores-rejilla.bones.json'
import _perdidas_rejilla from './perdidas-rejilla.bones.json'
import _mascotas_rejilla from './mascotas-rejilla.bones.json'
import _directorio_rejilla from './directorio-rejilla.bones.json'
import _carnet_tarjeta from './carnet-tarjeta.bones.json'
import _admin_verificaciones from './admin-verificaciones.bones.json'
import _paseador_solicitudes from './paseador-solicitudes.bones.json'
import _panel_metricas from './panel-metricas.bones.json'
import _admin_tabla from './admin-tabla.bones.json'
import _paseos_lista from './paseos-lista.bones.json'
import _perfil_cuenta from './perfil-cuenta.bones.json'

configureBoneyard({"color":"#e7edf0","darkColor":"#24404f","animate":"shimmer","shimmerColor":"#f4f8fa","darkShimmerColor":"#2e5266","speed":"1.6s","shimmerAngle":110,"stagger":60,"transition":220})

registerBones({
  "paseadores-rejilla": _paseadores_rejilla,
  "perdidas-rejilla": _perdidas_rejilla,
  "mascotas-rejilla": _mascotas_rejilla,
  "directorio-rejilla": _directorio_rejilla,
  "carnet-tarjeta": _carnet_tarjeta,
  "admin-verificaciones": _admin_verificaciones,
  "paseador-solicitudes": _paseador_solicitudes,
  "panel-metricas": _panel_metricas,
  "admin-tabla": _admin_tabla,
  "paseos-lista": _paseos_lista,
  "perfil-cuenta": _perfil_cuenta,
})
