-- Catalogo base de cobertura administrado por migraciones.

create unique index if not exists zonas_provincia_canton_unique
on public.zonas (lower(provincia), lower(canton));

insert into public.zonas (nombre, canton, provincia)
values
  ('San Jose', 'San Jose', 'San Jose'), ('Escazu', 'Escazu', 'San Jose'), ('Desamparados', 'Desamparados', 'San Jose'), ('Puriscal', 'Puriscal', 'San Jose'), ('Tarazu', 'Tarazu', 'San Jose'), ('Aserri', 'Aserri', 'San Jose'), ('Mora', 'Mora', 'San Jose'), ('Goicoechea', 'Goicoechea', 'San Jose'), ('Santa Ana', 'Santa Ana', 'San Jose'), ('Alajuelita', 'Alajuelita', 'San Jose'), ('Vazquez de Coronado', 'Vazquez de Coronado', 'San Jose'), ('Acosta', 'Acosta', 'San Jose'), ('Tibas', 'Tibas', 'San Jose'), ('Moravia', 'Moravia', 'San Jose'), ('Montes de Oca', 'Montes de Oca', 'San Jose'), ('Turrubares', 'Turrubares', 'San Jose'), ('Dota', 'Dota', 'San Jose'), ('Curridabat', 'Curridabat', 'San Jose'), ('Perez Zeledon', 'Perez Zeledon', 'San Jose'), ('Leon Cortes Castro', 'Leon Cortes Castro', 'San Jose'),
  ('Alajuela', 'Alajuela', 'Alajuela'), ('San Ramon', 'San Ramon', 'Alajuela'), ('Grecia', 'Grecia', 'Alajuela'), ('San Mateo', 'San Mateo', 'Alajuela'), ('Atenas', 'Atenas', 'Alajuela'), ('Naranjo', 'Naranjo', 'Alajuela'), ('Palmares', 'Palmares', 'Alajuela'), ('Poas', 'Poas', 'Alajuela'), ('Orotina', 'Orotina', 'Alajuela'), ('San Carlos', 'San Carlos', 'Alajuela'), ('Zarcero', 'Zarcero', 'Alajuela'), ('Sarchi', 'Sarchi', 'Alajuela'), ('Upala', 'Upala', 'Alajuela'), ('Los Chiles', 'Los Chiles', 'Alajuela'), ('Guatuso', 'Guatuso', 'Alajuela'), ('Rio Cuarto', 'Rio Cuarto', 'Alajuela'),
  ('Cartago', 'Cartago', 'Cartago'), ('Paraiso', 'Paraiso', 'Cartago'), ('La Union', 'La Union', 'Cartago'), ('Jimenez', 'Jimenez', 'Cartago'), ('Turrialba', 'Turrialba', 'Cartago'), ('Alvarado', 'Alvarado', 'Cartago'), ('Oreamuno', 'Oreamuno', 'Cartago'), ('El Guarco', 'El Guarco', 'Cartago'),
  ('Heredia', 'Heredia', 'Heredia'), ('Barva', 'Barva', 'Heredia'), ('Santo Domingo', 'Santo Domingo', 'Heredia'), ('Santa Barbara', 'Santa Barbara', 'Heredia'), ('San Rafael', 'San Rafael', 'Heredia'), ('San Isidro', 'San Isidro', 'Heredia'), ('Belen', 'Belen', 'Heredia'), ('Flores', 'Flores', 'Heredia'), ('San Pablo', 'San Pablo', 'Heredia'), ('Sarapiqui', 'Sarapiqui', 'Heredia'),
  ('Liberia', 'Liberia', 'Guanacaste'), ('Nicoya', 'Nicoya', 'Guanacaste'), ('Santa Cruz', 'Santa Cruz', 'Guanacaste'), ('Bagaces', 'Bagaces', 'Guanacaste'), ('Carrillo', 'Carrillo', 'Guanacaste'), ('Canas', 'Canas', 'Guanacaste'), ('Abangares', 'Abangares', 'Guanacaste'), ('Tilaran', 'Tilaran', 'Guanacaste'), ('Nandayure', 'Nandayure', 'Guanacaste'), ('La Cruz', 'La Cruz', 'Guanacaste'), ('Hojancha', 'Hojancha', 'Guanacaste'),
  ('Puntarenas', 'Puntarenas', 'Puntarenas'), ('Esparza', 'Esparza', 'Puntarenas'), ('Buenos Aires', 'Buenos Aires', 'Puntarenas'), ('Montes de Oro', 'Montes de Oro', 'Puntarenas'), ('Osa', 'Osa', 'Puntarenas'), ('Quepos', 'Quepos', 'Puntarenas'), ('Golfito', 'Golfito', 'Puntarenas'), ('Coto Brus', 'Coto Brus', 'Puntarenas'), ('Parrita', 'Parrita', 'Puntarenas'), ('Corredores', 'Corredores', 'Puntarenas'), ('Garabito', 'Garabito', 'Puntarenas'), ('Monteverde', 'Monteverde', 'Puntarenas'), ('Puerto Jimenez', 'Puerto Jimenez', 'Puntarenas'),
  ('Limon', 'Limon', 'Limon'), ('Pococi', 'Pococi', 'Limon'), ('Siquirres', 'Siquirres', 'Limon'), ('Talamanca', 'Talamanca', 'Limon'), ('Matina', 'Matina', 'Limon'), ('Guacimo', 'Guacimo', 'Limon')
on conflict (lower(provincia), lower(canton)) do nothing;