-- Catálogo completo de zonas de Costa Rica.
-- Fuente de referencia: División Territorial Administrativa 2026 (IGN / Registro Nacional).
-- Total esperado: 7 provincias, 84 cantones y 494 distritos.

-- Garantiza que la tabla pueda almacenar el distrito.
alter table public.zonas
    add column if not exists distrito varchar(100);

-- El índice anterior solo permitía un registro por cantón.
drop index if exists public.zonas_provincia_canton_unique;

-- Cada zona queda identificada por provincia + cantón + distrito.
create unique index if not exists zonas_provincia_canton_distrito_unique
on public.zonas (lower(provincia), lower(canton), lower(distrito));

-- Elimina registros antiguos sembrados únicamente a nivel de cantón.
delete from public.zonas
where distrito is null;

insert into public.zonas (nombre, distrito, canton, provincia)
values
    ('Carmen', 'Carmen', 'San José', 'San José'),
    ('Merced', 'Merced', 'San José', 'San José'),
    ('Hospital', 'Hospital', 'San José', 'San José'),
    ('Catedral', 'Catedral', 'San José', 'San José'),
    ('Zapote', 'Zapote', 'San José', 'San José'),
    ('San Francisco de Dos Ríos', 'San Francisco de Dos Ríos', 'San José', 'San José'),
    ('Uruca', 'Uruca', 'San José', 'San José'),
    ('Mata Redonda', 'Mata Redonda', 'San José', 'San José'),
    ('Pavas', 'Pavas', 'San José', 'San José'),
    ('Hatillo', 'Hatillo', 'San José', 'San José'),
    ('San Sebastián', 'San Sebastián', 'San José', 'San José'),
    ('Escazú', 'Escazú', 'Escazú', 'San José'),
    ('San Antonio', 'San Antonio', 'Escazú', 'San José'),
    ('San Rafael', 'San Rafael', 'Escazú', 'San José'),
    ('Desamparados', 'Desamparados', 'Desamparados', 'San José'),
    ('San Miguel', 'San Miguel', 'Desamparados', 'San José'),
    ('San Juan de Dios', 'San Juan de Dios', 'Desamparados', 'San José'),
    ('San Rafael Arriba', 'San Rafael Arriba', 'Desamparados', 'San José'),
    ('San Antonio', 'San Antonio', 'Desamparados', 'San José'),
    ('Frailes', 'Frailes', 'Desamparados', 'San José'),
    ('Patarrá', 'Patarrá', 'Desamparados', 'San José'),
    ('San Cristóbal', 'San Cristóbal', 'Desamparados', 'San José'),
    ('Rosario', 'Rosario', 'Desamparados', 'San José'),
    ('Damas', 'Damas', 'Desamparados', 'San José'),
    ('San Rafael Abajo', 'San Rafael Abajo', 'Desamparados', 'San José'),
    ('Gravilias', 'Gravilias', 'Desamparados', 'San José'),
    ('Los Guido', 'Los Guido', 'Desamparados', 'San José'),
    ('Santiago', 'Santiago', 'Puriscal', 'San José'),
    ('Mercedes Sur', 'Mercedes Sur', 'Puriscal', 'San José'),
    ('Barbacoas', 'Barbacoas', 'Puriscal', 'San José'),
    ('Grifo Alto', 'Grifo Alto', 'Puriscal', 'San José'),
    ('San Rafael', 'San Rafael', 'Puriscal', 'San José'),
    ('Candelarita', 'Candelarita', 'Puriscal', 'San José'),
    ('Desamparaditos', 'Desamparaditos', 'Puriscal', 'San José'),
    ('San Antonio', 'San Antonio', 'Puriscal', 'San José'),
    ('Chires', 'Chires', 'Puriscal', 'San José'),
    ('San Marcos', 'San Marcos', 'Tarrazú', 'San José'),
    ('San Lorenzo', 'San Lorenzo', 'Tarrazú', 'San José'),
    ('San Carlos', 'San Carlos', 'Tarrazú', 'San José'),
    ('Aserrí', 'Aserrí', 'Aserrí', 'San José'),
    ('Tarbaca', 'Tarbaca', 'Aserrí', 'San José'),
    ('Vuelta de Jorco', 'Vuelta de Jorco', 'Aserrí', 'San José'),
    ('San Gabriel', 'San Gabriel', 'Aserrí', 'San José'),
    ('Legua', 'Legua', 'Aserrí', 'San José'),
    ('Monterrey', 'Monterrey', 'Aserrí', 'San José'),
    ('Salitrillos', 'Salitrillos', 'Aserrí', 'San José'),
    ('Colón', 'Colón', 'Mora', 'San José'),
    ('Guayabo', 'Guayabo', 'Mora', 'San José'),
    ('Tabarcia', 'Tabarcia', 'Mora', 'San José'),
    ('Piedras Negras', 'Piedras Negras', 'Mora', 'San José'),
    ('Picagres', 'Picagres', 'Mora', 'San José'),
    ('Jaris', 'Jaris', 'Mora', 'San José'),
    ('Quitirrisí', 'Quitirrisí', 'Mora', 'San José'),
    ('Guadalupe', 'Guadalupe', 'Goicoechea', 'San José'),
    ('San Francisco', 'San Francisco', 'Goicoechea', 'San José'),
    ('Calle Blancos', 'Calle Blancos', 'Goicoechea', 'San José'),
    ('Mata de Plátano', 'Mata de Plátano', 'Goicoechea', 'San José'),
    ('Ipís', 'Ipís', 'Goicoechea', 'San José'),
    ('Rancho Redondo', 'Rancho Redondo', 'Goicoechea', 'San José'),
    ('Purral', 'Purral', 'Goicoechea', 'San José'),
    ('Santa Ana', 'Santa Ana', 'Santa Ana', 'San José'),
    ('Salitral', 'Salitral', 'Santa Ana', 'San José'),
    ('Pozos', 'Pozos', 'Santa Ana', 'San José'),
    ('Uruca', 'Uruca', 'Santa Ana', 'San José'),
    ('Piedades', 'Piedades', 'Santa Ana', 'San José'),
    ('Brasil', 'Brasil', 'Santa Ana', 'San José'),
    ('Alajuelita', 'Alajuelita', 'Alajuelita', 'San José'),
    ('San Josecito', 'San Josecito', 'Alajuelita', 'San José'),
    ('San Antonio', 'San Antonio', 'Alajuelita', 'San José'),
    ('Concepción', 'Concepción', 'Alajuelita', 'San José'),
    ('San Felipe', 'San Felipe', 'Alajuelita', 'San José'),
    ('San Isidro', 'San Isidro', 'Vázquez de Coronado', 'San José'),
    ('San Rafael', 'San Rafael', 'Vázquez de Coronado', 'San José'),
    ('Dulce Nombre de Jesús', 'Dulce Nombre de Jesús', 'Vázquez de Coronado', 'San José'),
    ('Patalillo', 'Patalillo', 'Vázquez de Coronado', 'San José'),
    ('Cascajal', 'Cascajal', 'Vázquez de Coronado', 'San José'),
    ('San Ignacio', 'San Ignacio', 'Acosta', 'San José'),
    ('Guaitil', 'Guaitil', 'Acosta', 'San José'),
    ('Palmichal', 'Palmichal', 'Acosta', 'San José'),
    ('Cangrejal', 'Cangrejal', 'Acosta', 'San José'),
    ('Sabanillas', 'Sabanillas', 'Acosta', 'San José'),
    ('San Juan', 'San Juan', 'Tibás', 'San José'),
    ('Cinco Esquinas', 'Cinco Esquinas', 'Tibás', 'San José'),
    ('Anselmo Llorente', 'Anselmo Llorente', 'Tibás', 'San José'),
    ('León XIII', 'León XIII', 'Tibás', 'San José'),
    ('Colima', 'Colima', 'Tibás', 'San José'),
    ('San Vicente', 'San Vicente', 'Moravia', 'San José'),
    ('San Jerónimo', 'San Jerónimo', 'Moravia', 'San José'),
    ('La Trinidad', 'La Trinidad', 'Moravia', 'San José'),
    ('San Pedro', 'San Pedro', 'Montes de Oca', 'San José'),
    ('Sabanilla', 'Sabanilla', 'Montes de Oca', 'San José'),
    ('Mercedes', 'Mercedes', 'Montes de Oca', 'San José'),
    ('San Rafael', 'San Rafael', 'Montes de Oca', 'San José'),
    ('San Pablo', 'San Pablo', 'Turrubares', 'San José'),
    ('San Pedro', 'San Pedro', 'Turrubares', 'San José'),
    ('San Juan de Mata', 'San Juan de Mata', 'Turrubares', 'San José'),
    ('San Luis', 'San Luis', 'Turrubares', 'San José'),
    ('Carara', 'Carara', 'Turrubares', 'San José'),
    ('Santa María', 'Santa María', 'Dota', 'San José'),
    ('Jardín', 'Jardín', 'Dota', 'San José'),
    ('Copey', 'Copey', 'Dota', 'San José'),
    ('Curridabat', 'Curridabat', 'Curridabat', 'San José'),
    ('Granadilla', 'Granadilla', 'Curridabat', 'San José'),
    ('Sánchez', 'Sánchez', 'Curridabat', 'San José'),
    ('Tirrases', 'Tirrases', 'Curridabat', 'San José'),
    ('San Isidro de El General', 'San Isidro de El General', 'Pérez Zeledón', 'San José'),
    ('El General', 'El General', 'Pérez Zeledón', 'San José'),
    ('Daniel Flores', 'Daniel Flores', 'Pérez Zeledón', 'San José'),
    ('Rivas', 'Rivas', 'Pérez Zeledón', 'San José'),
    ('San Pedro', 'San Pedro', 'Pérez Zeledón', 'San José'),
    ('Platanares', 'Platanares', 'Pérez Zeledón', 'San José'),
    ('Pejivalle', 'Pejivalle', 'Pérez Zeledón', 'San José'),
    ('Cajón', 'Cajón', 'Pérez Zeledón', 'San José'),
    ('Barú', 'Barú', 'Pérez Zeledón', 'San José'),
    ('Río Nuevo', 'Río Nuevo', 'Pérez Zeledón', 'San José'),
    ('Páramo', 'Páramo', 'Pérez Zeledón', 'San José'),
    ('La Amistad', 'La Amistad', 'Pérez Zeledón', 'San José'),
    ('San Pablo', 'San Pablo', 'León Cortés Castro', 'San José'),
    ('San Andrés', 'San Andrés', 'León Cortés Castro', 'San José'),
    ('Llano Bonito', 'Llano Bonito', 'León Cortés Castro', 'San José'),
    ('San Isidro', 'San Isidro', 'León Cortés Castro', 'San José'),
    ('Santa Cruz', 'Santa Cruz', 'León Cortés Castro', 'San José'),
    ('San Antonio', 'San Antonio', 'León Cortés Castro', 'San José'),
    ('Alajuela', 'Alajuela', 'Alajuela', 'Alajuela'),
    ('San José', 'San José', 'Alajuela', 'Alajuela'),
    ('Carrizal', 'Carrizal', 'Alajuela', 'Alajuela'),
    ('San Antonio', 'San Antonio', 'Alajuela', 'Alajuela'),
    ('Guácima', 'Guácima', 'Alajuela', 'Alajuela'),
    ('San Isidro', 'San Isidro', 'Alajuela', 'Alajuela'),
    ('Sabanilla', 'Sabanilla', 'Alajuela', 'Alajuela'),
    ('San Rafael', 'San Rafael', 'Alajuela', 'Alajuela'),
    ('Río Segundo', 'Río Segundo', 'Alajuela', 'Alajuela'),
    ('Desamparados', 'Desamparados', 'Alajuela', 'Alajuela'),
    ('Turrúcares', 'Turrúcares', 'Alajuela', 'Alajuela'),
    ('Tambor', 'Tambor', 'Alajuela', 'Alajuela'),
    ('Garita', 'Garita', 'Alajuela', 'Alajuela'),
    ('Sarapiquí', 'Sarapiquí', 'Alajuela', 'Alajuela'),
    ('San Ramón', 'San Ramón', 'San Ramón', 'Alajuela'),
    ('Santiago', 'Santiago', 'San Ramón', 'Alajuela'),
    ('San Juan', 'San Juan', 'San Ramón', 'Alajuela'),
    ('Piedades Norte', 'Piedades Norte', 'San Ramón', 'Alajuela'),
    ('Piedades Sur', 'Piedades Sur', 'San Ramón', 'Alajuela'),
    ('San Rafael', 'San Rafael', 'San Ramón', 'Alajuela'),
    ('San Isidro', 'San Isidro', 'San Ramón', 'Alajuela'),
    ('Ángeles', 'Ángeles', 'San Ramón', 'Alajuela'),
    ('Alfaro', 'Alfaro', 'San Ramón', 'Alajuela'),
    ('Volio', 'Volio', 'San Ramón', 'Alajuela'),
    ('Concepción', 'Concepción', 'San Ramón', 'Alajuela'),
    ('Zapotal', 'Zapotal', 'San Ramón', 'Alajuela'),
    ('Peñas Blancas', 'Peñas Blancas', 'San Ramón', 'Alajuela'),
    ('San Lorenzo', 'San Lorenzo', 'San Ramón', 'Alajuela'),
    ('Grecia', 'Grecia', 'Grecia', 'Alajuela'),
    ('San Isidro', 'San Isidro', 'Grecia', 'Alajuela'),
    ('San José', 'San José', 'Grecia', 'Alajuela'),
    ('San Roque', 'San Roque', 'Grecia', 'Alajuela'),
    ('Tacares', 'Tacares', 'Grecia', 'Alajuela'),
    ('Puente de Piedra', 'Puente de Piedra', 'Grecia', 'Alajuela'),
    ('Bolívar', 'Bolívar', 'Grecia', 'Alajuela'),
    ('San Mateo', 'San Mateo', 'San Mateo', 'Alajuela'),
    ('Desmonte', 'Desmonte', 'San Mateo', 'Alajuela'),
    ('Jesús María', 'Jesús María', 'San Mateo', 'Alajuela'),
    ('Labrador', 'Labrador', 'San Mateo', 'Alajuela'),
    ('Atenas', 'Atenas', 'Atenas', 'Alajuela'),
    ('Jesús', 'Jesús', 'Atenas', 'Alajuela'),
    ('Mercedes', 'Mercedes', 'Atenas', 'Alajuela'),
    ('San Isidro', 'San Isidro', 'Atenas', 'Alajuela'),
    ('Concepción', 'Concepción', 'Atenas', 'Alajuela'),
    ('San José', 'San José', 'Atenas', 'Alajuela'),
    ('Santa Eulalia', 'Santa Eulalia', 'Atenas', 'Alajuela'),
    ('Escobal', 'Escobal', 'Atenas', 'Alajuela'),
    ('Naranjo', 'Naranjo', 'Naranjo', 'Alajuela'),
    ('San Miguel', 'San Miguel', 'Naranjo', 'Alajuela'),
    ('San José', 'San José', 'Naranjo', 'Alajuela'),
    ('Cirrí Sur', 'Cirrí Sur', 'Naranjo', 'Alajuela'),
    ('San Jerónimo', 'San Jerónimo', 'Naranjo', 'Alajuela'),
    ('San Juan', 'San Juan', 'Naranjo', 'Alajuela'),
    ('El Rosario', 'El Rosario', 'Naranjo', 'Alajuela'),
    ('Palmitos', 'Palmitos', 'Naranjo', 'Alajuela'),
    ('Palmares', 'Palmares', 'Palmares', 'Alajuela'),
    ('Zaragoza', 'Zaragoza', 'Palmares', 'Alajuela'),
    ('Buenos Aires', 'Buenos Aires', 'Palmares', 'Alajuela'),
    ('Santiago', 'Santiago', 'Palmares', 'Alajuela'),
    ('Candelaria', 'Candelaria', 'Palmares', 'Alajuela'),
    ('Esquipulas', 'Esquipulas', 'Palmares', 'Alajuela'),
    ('La Granja', 'La Granja', 'Palmares', 'Alajuela'),
    ('San Pedro', 'San Pedro', 'Poás', 'Alajuela'),
    ('San Juan', 'San Juan', 'Poás', 'Alajuela'),
    ('San Rafael', 'San Rafael', 'Poás', 'Alajuela'),
    ('Carrillos', 'Carrillos', 'Poás', 'Alajuela'),
    ('Sabana Redonda', 'Sabana Redonda', 'Poás', 'Alajuela'),
    ('Orotina', 'Orotina', 'Orotina', 'Alajuela'),
    ('El Mastate', 'El Mastate', 'Orotina', 'Alajuela'),
    ('Hacienda Vieja', 'Hacienda Vieja', 'Orotina', 'Alajuela'),
    ('Coyolar', 'Coyolar', 'Orotina', 'Alajuela'),
    ('La Ceiba', 'La Ceiba', 'Orotina', 'Alajuela'),
    ('Quesada', 'Quesada', 'San Carlos', 'Alajuela'),
    ('Florencia', 'Florencia', 'San Carlos', 'Alajuela'),
    ('Buenavista', 'Buenavista', 'San Carlos', 'Alajuela'),
    ('Aguas Zarcas', 'Aguas Zarcas', 'San Carlos', 'Alajuela'),
    ('Venecia', 'Venecia', 'San Carlos', 'Alajuela'),
    ('Pital', 'Pital', 'San Carlos', 'Alajuela'),
    ('La Fortuna', 'La Fortuna', 'San Carlos', 'Alajuela'),
    ('La Tigra', 'La Tigra', 'San Carlos', 'Alajuela'),
    ('La Palmera', 'La Palmera', 'San Carlos', 'Alajuela'),
    ('Venado', 'Venado', 'San Carlos', 'Alajuela'),
    ('Cutris', 'Cutris', 'San Carlos', 'Alajuela'),
    ('Monterrey', 'Monterrey', 'San Carlos', 'Alajuela'),
    ('Pocosol', 'Pocosol', 'San Carlos', 'Alajuela'),
    ('Zarcero', 'Zarcero', 'Zarcero', 'Alajuela'),
    ('Laguna', 'Laguna', 'Zarcero', 'Alajuela'),
    ('Tapesco', 'Tapesco', 'Zarcero', 'Alajuela'),
    ('Guadalupe', 'Guadalupe', 'Zarcero', 'Alajuela'),
    ('Palmira', 'Palmira', 'Zarcero', 'Alajuela'),
    ('Zapote', 'Zapote', 'Zarcero', 'Alajuela'),
    ('Brisas', 'Brisas', 'Zarcero', 'Alajuela'),
    ('Sarchí Norte', 'Sarchí Norte', 'Sarchí', 'Alajuela'),
    ('Sarchí Sur', 'Sarchí Sur', 'Sarchí', 'Alajuela'),
    ('Toro Amarillo', 'Toro Amarillo', 'Sarchí', 'Alajuela'),
    ('San Pedro', 'San Pedro', 'Sarchí', 'Alajuela'),
    ('Rodríguez', 'Rodríguez', 'Sarchí', 'Alajuela'),
    ('Upala', 'Upala', 'Upala', 'Alajuela'),
    ('Aguas Claras', 'Aguas Claras', 'Upala', 'Alajuela'),
    ('San José o Pizote', 'San José o Pizote', 'Upala', 'Alajuela'),
    ('Bijagua', 'Bijagua', 'Upala', 'Alajuela'),
    ('Delicias', 'Delicias', 'Upala', 'Alajuela'),
    ('Dos Ríos', 'Dos Ríos', 'Upala', 'Alajuela'),
    ('Yolillal', 'Yolillal', 'Upala', 'Alajuela'),
    ('Canalete', 'Canalete', 'Upala', 'Alajuela'),
    ('Los Chiles', 'Los Chiles', 'Los Chiles', 'Alajuela'),
    ('Caño Negro', 'Caño Negro', 'Los Chiles', 'Alajuela'),
    ('El Amparo', 'El Amparo', 'Los Chiles', 'Alajuela'),
    ('San Jorge', 'San Jorge', 'Los Chiles', 'Alajuela'),
    ('San Rafael', 'San Rafael', 'Guatuso', 'Alajuela'),
    ('Buenavista', 'Buenavista', 'Guatuso', 'Alajuela'),
    ('Cote', 'Cote', 'Guatuso', 'Alajuela'),
    ('Katira', 'Katira', 'Guatuso', 'Alajuela'),
    ('Río Cuarto', 'Río Cuarto', 'Río Cuarto', 'Alajuela'),
    ('Santa Rita', 'Santa Rita', 'Río Cuarto', 'Alajuela'),
    ('Santa Isabel', 'Santa Isabel', 'Río Cuarto', 'Alajuela'),
    ('Oriental', 'Oriental', 'Cartago', 'Cartago'),
    ('Occidental', 'Occidental', 'Cartago', 'Cartago'),
    ('Carmen', 'Carmen', 'Cartago', 'Cartago'),
    ('San Nicolás', 'San Nicolás', 'Cartago', 'Cartago'),
    ('Aguacaliente o San Francisco', 'Aguacaliente o San Francisco', 'Cartago', 'Cartago'),
    ('Guadalupe o Arenilla', 'Guadalupe o Arenilla', 'Cartago', 'Cartago'),
    ('Corralillo', 'Corralillo', 'Cartago', 'Cartago'),
    ('Tierra Blanca', 'Tierra Blanca', 'Cartago', 'Cartago'),
    ('Dulce Nombre', 'Dulce Nombre', 'Cartago', 'Cartago'),
    ('Llano Grande', 'Llano Grande', 'Cartago', 'Cartago'),
    ('Quebradilla', 'Quebradilla', 'Cartago', 'Cartago'),
    ('Paraíso', 'Paraíso', 'Paraíso', 'Cartago'),
    ('Santiago', 'Santiago', 'Paraíso', 'Cartago'),
    ('Orosi', 'Orosi', 'Paraíso', 'Cartago'),
    ('Cachí', 'Cachí', 'Paraíso', 'Cartago'),
    ('Llanos de Santa Lucía', 'Llanos de Santa Lucía', 'Paraíso', 'Cartago'),
    ('Birrisito', 'Birrisito', 'Paraíso', 'Cartago'),
    ('Tres Ríos', 'Tres Ríos', 'La Unión', 'Cartago'),
    ('San Diego', 'San Diego', 'La Unión', 'Cartago'),
    ('San Juan', 'San Juan', 'La Unión', 'Cartago'),
    ('San Rafael', 'San Rafael', 'La Unión', 'Cartago'),
    ('Concepción', 'Concepción', 'La Unión', 'Cartago'),
    ('Dulce Nombre', 'Dulce Nombre', 'La Unión', 'Cartago'),
    ('San Ramón', 'San Ramón', 'La Unión', 'Cartago'),
    ('Río Azul', 'Río Azul', 'La Unión', 'Cartago'),
    ('Juan Viñas', 'Juan Viñas', 'Jiménez', 'Cartago'),
    ('Tucurrique', 'Tucurrique', 'Jiménez', 'Cartago'),
    ('Pejibaye', 'Pejibaye', 'Jiménez', 'Cartago'),
    ('La Victoria', 'La Victoria', 'Jiménez', 'Cartago'),
    ('Turrialba', 'Turrialba', 'Turrialba', 'Cartago'),
    ('La Suiza', 'La Suiza', 'Turrialba', 'Cartago'),
    ('Peralta', 'Peralta', 'Turrialba', 'Cartago'),
    ('Santa Cruz', 'Santa Cruz', 'Turrialba', 'Cartago'),
    ('Santa Teresita', 'Santa Teresita', 'Turrialba', 'Cartago'),
    ('Pavones', 'Pavones', 'Turrialba', 'Cartago'),
    ('Tuis', 'Tuis', 'Turrialba', 'Cartago'),
    ('Tayutic', 'Tayutic', 'Turrialba', 'Cartago'),
    ('Santa Rosa', 'Santa Rosa', 'Turrialba', 'Cartago'),
    ('Tres Equis', 'Tres Equis', 'Turrialba', 'Cartago'),
    ('La Isabel', 'La Isabel', 'Turrialba', 'Cartago'),
    ('Chirripó', 'Chirripó', 'Turrialba', 'Cartago'),
    ('Pacayas', 'Pacayas', 'Alvarado', 'Cartago'),
    ('Cervantes', 'Cervantes', 'Alvarado', 'Cartago'),
    ('Capellades', 'Capellades', 'Alvarado', 'Cartago'),
    ('San Rafael', 'San Rafael', 'Oreamuno', 'Cartago'),
    ('Cot', 'Cot', 'Oreamuno', 'Cartago'),
    ('Potrero Cerrado', 'Potrero Cerrado', 'Oreamuno', 'Cartago'),
    ('Cipreses', 'Cipreses', 'Oreamuno', 'Cartago'),
    ('Santa Rosa', 'Santa Rosa', 'Oreamuno', 'Cartago'),
    ('El Tejar', 'El Tejar', 'El Guarco', 'Cartago'),
    ('San Isidro', 'San Isidro', 'El Guarco', 'Cartago'),
    ('Tobosi', 'Tobosi', 'El Guarco', 'Cartago'),
    ('Patio de Agua', 'Patio de Agua', 'El Guarco', 'Cartago'),
    ('Heredia', 'Heredia', 'Heredia', 'Heredia'),
    ('Mercedes', 'Mercedes', 'Heredia', 'Heredia'),
    ('San Francisco', 'San Francisco', 'Heredia', 'Heredia'),
    ('Ulloa', 'Ulloa', 'Heredia', 'Heredia'),
    ('Varablanca', 'Varablanca', 'Heredia', 'Heredia'),
    ('Barva', 'Barva', 'Barva', 'Heredia'),
    ('San Pedro', 'San Pedro', 'Barva', 'Heredia'),
    ('San Pablo', 'San Pablo', 'Barva', 'Heredia'),
    ('San Roque', 'San Roque', 'Barva', 'Heredia'),
    ('Santa Lucía', 'Santa Lucía', 'Barva', 'Heredia'),
    ('San José de la Montaña', 'San José de la Montaña', 'Barva', 'Heredia'),
    ('Puente Salas', 'Puente Salas', 'Barva', 'Heredia'),
    ('Santo Domingo', 'Santo Domingo', 'Santo Domingo', 'Heredia'),
    ('San Vicente', 'San Vicente', 'Santo Domingo', 'Heredia'),
    ('San Miguel', 'San Miguel', 'Santo Domingo', 'Heredia'),
    ('Paracito', 'Paracito', 'Santo Domingo', 'Heredia'),
    ('Santo Tomás', 'Santo Tomás', 'Santo Domingo', 'Heredia'),
    ('Santa Rosa', 'Santa Rosa', 'Santo Domingo', 'Heredia'),
    ('Tures', 'Tures', 'Santo Domingo', 'Heredia'),
    ('Pará', 'Pará', 'Santo Domingo', 'Heredia'),
    ('Santa Bárbara', 'Santa Bárbara', 'Santa Bárbara', 'Heredia'),
    ('San Pedro', 'San Pedro', 'Santa Bárbara', 'Heredia'),
    ('San Juan', 'San Juan', 'Santa Bárbara', 'Heredia'),
    ('Jesús', 'Jesús', 'Santa Bárbara', 'Heredia'),
    ('Santo Domingo', 'Santo Domingo', 'Santa Bárbara', 'Heredia'),
    ('Purabá', 'Purabá', 'Santa Bárbara', 'Heredia'),
    ('San Rafael', 'San Rafael', 'San Rafael', 'Heredia'),
    ('San Josecito', 'San Josecito', 'San Rafael', 'Heredia'),
    ('Santiago', 'Santiago', 'San Rafael', 'Heredia'),
    ('Ángeles', 'Ángeles', 'San Rafael', 'Heredia'),
    ('Concepción', 'Concepción', 'San Rafael', 'Heredia'),
    ('San Isidro', 'San Isidro', 'San Isidro', 'Heredia'),
    ('San José', 'San José', 'San Isidro', 'Heredia'),
    ('Concepción', 'Concepción', 'San Isidro', 'Heredia'),
    ('San Francisco', 'San Francisco', 'San Isidro', 'Heredia'),
    ('San Antonio', 'San Antonio', 'Belén', 'Heredia'),
    ('La Ribera', 'La Ribera', 'Belén', 'Heredia'),
    ('La Asunción', 'La Asunción', 'Belén', 'Heredia'),
    ('San Joaquín', 'San Joaquín', 'Flores', 'Heredia'),
    ('Barrantes', 'Barrantes', 'Flores', 'Heredia'),
    ('Llorente', 'Llorente', 'Flores', 'Heredia'),
    ('San Pablo', 'San Pablo', 'San Pablo', 'Heredia'),
    ('Rincón de Sabanilla', 'Rincón de Sabanilla', 'San Pablo', 'Heredia'),
    ('Puerto Viejo', 'Puerto Viejo', 'Sarapiquí', 'Heredia'),
    ('La Virgen', 'La Virgen', 'Sarapiquí', 'Heredia'),
    ('Las Horquetas', 'Las Horquetas', 'Sarapiquí', 'Heredia'),
    ('Llanuras del Gaspar', 'Llanuras del Gaspar', 'Sarapiquí', 'Heredia'),
    ('Cureña', 'Cureña', 'Sarapiquí', 'Heredia'),
    ('Liberia', 'Liberia', 'Liberia', 'Guanacaste'),
    ('Cañas Dulces', 'Cañas Dulces', 'Liberia', 'Guanacaste'),
    ('Mayorga', 'Mayorga', 'Liberia', 'Guanacaste'),
    ('Nacascolo', 'Nacascolo', 'Liberia', 'Guanacaste'),
    ('Curubandé', 'Curubandé', 'Liberia', 'Guanacaste'),
    ('Nicoya', 'Nicoya', 'Nicoya', 'Guanacaste'),
    ('Mansión', 'Mansión', 'Nicoya', 'Guanacaste'),
    ('San Antonio', 'San Antonio', 'Nicoya', 'Guanacaste'),
    ('Quebrada Honda', 'Quebrada Honda', 'Nicoya', 'Guanacaste'),
    ('Sámara', 'Sámara', 'Nicoya', 'Guanacaste'),
    ('Nosara', 'Nosara', 'Nicoya', 'Guanacaste'),
    ('Belén de Nosarita', 'Belén de Nosarita', 'Nicoya', 'Guanacaste'),
    ('Santa Cruz', 'Santa Cruz', 'Santa Cruz', 'Guanacaste'),
    ('Bolsón', 'Bolsón', 'Santa Cruz', 'Guanacaste'),
    ('Veintisiete de Abril', 'Veintisiete de Abril', 'Santa Cruz', 'Guanacaste'),
    ('Tempate', 'Tempate', 'Santa Cruz', 'Guanacaste'),
    ('Cartagena', 'Cartagena', 'Santa Cruz', 'Guanacaste'),
    ('Cuajiniquil', 'Cuajiniquil', 'Santa Cruz', 'Guanacaste'),
    ('Diriá', 'Diriá', 'Santa Cruz', 'Guanacaste'),
    ('Cabo Velas', 'Cabo Velas', 'Santa Cruz', 'Guanacaste'),
    ('Tamarindo', 'Tamarindo', 'Santa Cruz', 'Guanacaste'),
    ('Bagaces', 'Bagaces', 'Bagaces', 'Guanacaste'),
    ('La Fortuna', 'La Fortuna', 'Bagaces', 'Guanacaste'),
    ('Mogote', 'Mogote', 'Bagaces', 'Guanacaste'),
    ('Río Naranjo', 'Río Naranjo', 'Bagaces', 'Guanacaste'),
    ('Pijije', 'Pijije', 'Bagaces', 'Guanacaste'),
    ('Filadelfia', 'Filadelfia', 'Carrillo', 'Guanacaste'),
    ('Palmira', 'Palmira', 'Carrillo', 'Guanacaste'),
    ('Sardinal', 'Sardinal', 'Carrillo', 'Guanacaste'),
    ('Belén', 'Belén', 'Carrillo', 'Guanacaste'),
    ('Cañas', 'Cañas', 'Cañas', 'Guanacaste'),
    ('Palmira', 'Palmira', 'Cañas', 'Guanacaste'),
    ('San Miguel', 'San Miguel', 'Cañas', 'Guanacaste'),
    ('Bebedero', 'Bebedero', 'Cañas', 'Guanacaste'),
    ('Porozal', 'Porozal', 'Cañas', 'Guanacaste'),
    ('Las Juntas', 'Las Juntas', 'Abangares', 'Guanacaste'),
    ('Sierra', 'Sierra', 'Abangares', 'Guanacaste'),
    ('San Juan', 'San Juan', 'Abangares', 'Guanacaste'),
    ('Colorado', 'Colorado', 'Abangares', 'Guanacaste'),
    ('Tilarán', 'Tilarán', 'Tilarán', 'Guanacaste'),
    ('Quebrada Grande', 'Quebrada Grande', 'Tilarán', 'Guanacaste'),
    ('Tronadora', 'Tronadora', 'Tilarán', 'Guanacaste'),
    ('Santa Rosa', 'Santa Rosa', 'Tilarán', 'Guanacaste'),
    ('Líbano', 'Líbano', 'Tilarán', 'Guanacaste'),
    ('Tierras Morenas', 'Tierras Morenas', 'Tilarán', 'Guanacaste'),
    ('Arenal', 'Arenal', 'Tilarán', 'Guanacaste'),
    ('Cabeceras', 'Cabeceras', 'Tilarán', 'Guanacaste'),
    ('Carmona', 'Carmona', 'Nandayure', 'Guanacaste'),
    ('Santa Rita', 'Santa Rita', 'Nandayure', 'Guanacaste'),
    ('Zapotal', 'Zapotal', 'Nandayure', 'Guanacaste'),
    ('San Pablo', 'San Pablo', 'Nandayure', 'Guanacaste'),
    ('Porvenir', 'Porvenir', 'Nandayure', 'Guanacaste'),
    ('Bejuco', 'Bejuco', 'Nandayure', 'Guanacaste'),
    ('La Cruz', 'La Cruz', 'La Cruz', 'Guanacaste'),
    ('Santa Cecilia', 'Santa Cecilia', 'La Cruz', 'Guanacaste'),
    ('La Garita', 'La Garita', 'La Cruz', 'Guanacaste'),
    ('Santa Elena', 'Santa Elena', 'La Cruz', 'Guanacaste'),
    ('Hojancha', 'Hojancha', 'Hojancha', 'Guanacaste'),
    ('Monte Romo', 'Monte Romo', 'Hojancha', 'Guanacaste'),
    ('Puerto Carrillo', 'Puerto Carrillo', 'Hojancha', 'Guanacaste'),
    ('Huacas', 'Huacas', 'Hojancha', 'Guanacaste'),
    ('Matambú', 'Matambú', 'Hojancha', 'Guanacaste'),
    ('Puntarenas', 'Puntarenas', 'Puntarenas', 'Puntarenas'),
    ('Pitahaya', 'Pitahaya', 'Puntarenas', 'Puntarenas'),
    ('Chomes', 'Chomes', 'Puntarenas', 'Puntarenas'),
    ('Lepanto', 'Lepanto', 'Puntarenas', 'Puntarenas'),
    ('Paquera', 'Paquera', 'Puntarenas', 'Puntarenas'),
    ('Manzanillo', 'Manzanillo', 'Puntarenas', 'Puntarenas'),
    ('Guacimal', 'Guacimal', 'Puntarenas', 'Puntarenas'),
    ('Barranca', 'Barranca', 'Puntarenas', 'Puntarenas'),
    ('Isla del Coco', 'Isla del Coco', 'Puntarenas', 'Puntarenas'),
    ('Cóbano', 'Cóbano', 'Puntarenas', 'Puntarenas'),
    ('Chacarita', 'Chacarita', 'Puntarenas', 'Puntarenas'),
    ('Chira', 'Chira', 'Puntarenas', 'Puntarenas'),
    ('Acapulco', 'Acapulco', 'Puntarenas', 'Puntarenas'),
    ('El Roble', 'El Roble', 'Puntarenas', 'Puntarenas'),
    ('Arancibia', 'Arancibia', 'Puntarenas', 'Puntarenas'),
    ('Espíritu Santo', 'Espíritu Santo', 'Esparza', 'Puntarenas'),
    ('San Juan Grande', 'San Juan Grande', 'Esparza', 'Puntarenas'),
    ('Macacona', 'Macacona', 'Esparza', 'Puntarenas'),
    ('San Rafael', 'San Rafael', 'Esparza', 'Puntarenas'),
    ('San Jerónimo', 'San Jerónimo', 'Esparza', 'Puntarenas'),
    ('Caldera', 'Caldera', 'Esparza', 'Puntarenas'),
    ('Buenos Aires', 'Buenos Aires', 'Buenos Aires', 'Puntarenas'),
    ('Volcán', 'Volcán', 'Buenos Aires', 'Puntarenas'),
    ('Potrero Grande', 'Potrero Grande', 'Buenos Aires', 'Puntarenas'),
    ('Boruca', 'Boruca', 'Buenos Aires', 'Puntarenas'),
    ('Pilas', 'Pilas', 'Buenos Aires', 'Puntarenas'),
    ('Colinas', 'Colinas', 'Buenos Aires', 'Puntarenas'),
    ('Chánguena', 'Chánguena', 'Buenos Aires', 'Puntarenas'),
    ('Biolley', 'Biolley', 'Buenos Aires', 'Puntarenas'),
    ('Brunka', 'Brunka', 'Buenos Aires', 'Puntarenas'),
    ('Cabagra', 'Cabagra', 'Buenos Aires', 'Puntarenas'),
    ('Miramar', 'Miramar', 'Montes de Oro', 'Puntarenas'),
    ('La Unión', 'La Unión', 'Montes de Oro', 'Puntarenas'),
    ('San Isidro', 'San Isidro', 'Montes de Oro', 'Puntarenas'),
    ('Puerto Cortés', 'Puerto Cortés', 'Osa', 'Puntarenas'),
    ('Palmar', 'Palmar', 'Osa', 'Puntarenas'),
    ('Sierpe', 'Sierpe', 'Osa', 'Puntarenas'),
    ('Bahía Ballena', 'Bahía Ballena', 'Osa', 'Puntarenas'),
    ('Piedras Blancas', 'Piedras Blancas', 'Osa', 'Puntarenas'),
    ('Bahía Drake', 'Bahía Drake', 'Osa', 'Puntarenas'),
    ('Quepos', 'Quepos', 'Quepos', 'Puntarenas'),
    ('Savegre', 'Savegre', 'Quepos', 'Puntarenas'),
    ('Naranjito', 'Naranjito', 'Quepos', 'Puntarenas'),
    ('Golfito', 'Golfito', 'Golfito', 'Puntarenas'),
    ('Guaycará', 'Guaycará', 'Golfito', 'Puntarenas'),
    ('Pavón', 'Pavón', 'Golfito', 'Puntarenas'),
    ('San Vito', 'San Vito', 'Coto Brus', 'Puntarenas'),
    ('Sabalito', 'Sabalito', 'Coto Brus', 'Puntarenas'),
    ('Aguabuena', 'Aguabuena', 'Coto Brus', 'Puntarenas'),
    ('Limoncito', 'Limoncito', 'Coto Brus', 'Puntarenas'),
    ('Pittier', 'Pittier', 'Coto Brus', 'Puntarenas'),
    ('Gutiérrez Braun', 'Gutiérrez Braun', 'Coto Brus', 'Puntarenas'),
    ('Parrita', 'Parrita', 'Parrita', 'Puntarenas'),
    ('Corredor', 'Corredor', 'Corredores', 'Puntarenas'),
    ('La Cuesta', 'La Cuesta', 'Corredores', 'Puntarenas'),
    ('Canoas', 'Canoas', 'Corredores', 'Puntarenas'),
    ('Laurel', 'Laurel', 'Corredores', 'Puntarenas'),
    ('Jacó', 'Jacó', 'Garabito', 'Puntarenas'),
    ('Tárcoles', 'Tárcoles', 'Garabito', 'Puntarenas'),
    ('Lagunillas', 'Lagunillas', 'Garabito', 'Puntarenas'),
    ('Monteverde', 'Monteverde', 'Monteverde', 'Puntarenas'),
    ('Puerto Jiménez', 'Puerto Jiménez', 'Puerto Jiménez', 'Puntarenas'),
    ('Limón', 'Limón', 'Limón', 'Limón'),
    ('Valle La Estrella', 'Valle La Estrella', 'Limón', 'Limón'),
    ('Río Blanco', 'Río Blanco', 'Limón', 'Limón'),
    ('Matama', 'Matama', 'Limón', 'Limón'),
    ('Guápiles', 'Guápiles', 'Pococí', 'Limón'),
    ('Jiménez', 'Jiménez', 'Pococí', 'Limón'),
    ('Rita', 'Rita', 'Pococí', 'Limón'),
    ('Roxana', 'Roxana', 'Pococí', 'Limón'),
    ('Cariari', 'Cariari', 'Pococí', 'Limón'),
    ('Colorado', 'Colorado', 'Pococí', 'Limón'),
    ('La Colonia', 'La Colonia', 'Pococí', 'Limón'),
    ('Siquirres', 'Siquirres', 'Siquirres', 'Limón'),
    ('Pacuarito', 'Pacuarito', 'Siquirres', 'Limón'),
    ('Florida', 'Florida', 'Siquirres', 'Limón'),
    ('Germania', 'Germania', 'Siquirres', 'Limón'),
    ('El Cairo', 'El Cairo', 'Siquirres', 'Limón'),
    ('Alegría', 'Alegría', 'Siquirres', 'Limón'),
    ('Reventazón', 'Reventazón', 'Siquirres', 'Limón'),
    ('Bratsi', 'Bratsi', 'Talamanca', 'Limón'),
    ('Sixaola', 'Sixaola', 'Talamanca', 'Limón'),
    ('Cahuita', 'Cahuita', 'Talamanca', 'Limón'),
    ('Telire', 'Telire', 'Talamanca', 'Limón'),
    ('Matina', 'Matina', 'Matina', 'Limón'),
    ('Batán', 'Batán', 'Matina', 'Limón'),
    ('Carrandí', 'Carrandí', 'Matina', 'Limón'),
    ('Guácimo', 'Guácimo', 'Guácimo', 'Limón'),
    ('Mercedes', 'Mercedes', 'Guácimo', 'Limón'),
    ('Pocora', 'Pocora', 'Guácimo', 'Limón'),
    ('Río Jiménez', 'Río Jiménez', 'Guácimo', 'Limón'),
    ('Duacarí', 'Duacarí', 'Guácimo', 'Limón')

on conflict (lower(provincia), lower(canton), lower(distrito))
do nothing;

-- Verificación rápida.
-- Debe devolver: 7 provincias, 84 cantones y 494 distritos.
select
    count(distinct provincia) as provincias,
    count(distinct (provincia, canton)) as cantones,
    count(*) as distritos
from public.zonas
where distrito is not null;
